### ISSUE TITLE
Module `navigation` does not exist in the Haste module map

### ISSUE THREAD

**Issue by Moustafa2050** [developer239/redux-react-native-wix-navigation-v2-with-auth#50]

**Comment by developer239** [comment]
@Moustafa2050 Oh, I am sorry about that. I will fix it tomorrow. This will be most likely a problem with some updated dependency.

**Comment by developer239** [comment]
Hmm, 🤔 I couldn't make the project run on my new computer even after reverting git history before greenkeeper run updates. I will have to get back to this later. Probably when RNN2 is compatible with react-native 59 (this version is going to include hooks)

**Comment by dnkodi** [comment]
Ran into the same issue and i fixed it by resetting the cache. You could do `npm start` since it has the reset cache flag. If not this worked for me `react-native start --reset-cache`

**Comment by Moustafa2050** [comment]
I will try it
Thanks alot

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by developer239** [comment]
@Moustafa2050 There was a bug in start command I used `node node_modules/react-native/local-cli/cli.js start -- --reset-cache` instead of `node node_modules/react-native/local-cli/cli.js start --reset-cache` now it should work properly. Thanks for noticing @dnkodi  🙂
